<form action="<?php echo $this->URL;?>/insert?navTabId=<?php echo $this->MODULE;?>" method="post" class="pageForm required-validate" onsubmit="return validateCallback(this, dialogAjaxDone)">
<div class="pageContent">
    <div class="pageFormContent" layoutH="58">
        <dl>
            <dt>名称：</dt><dd><input name="name" class="required" type="text"/></dd>
        </dl>
        <dl>
            <dt>真实名称：</dt><dd><input name="realname" class="required" type="text"/></dd>
        </dl>
        <dl>
            <dt>E-mail：</dt><dd><input name="email" class="required" type="text"/></dd>
        </dl>
        <dl class="nowrap">
            <dt>地址：</dt>
            <dd>
                <textarea class="editor" name="address" rows="4" cols="75"></textarea>
            </dd>
        </dl>
        <dl class="nowrap">
            <dt>角色：</dt>
            <dd>
                <select name="role_id" class="required">
                    <option value="1">管理员</option>
                </select>
            </dd>
        </dl>
    </div>
    <div class="formBar">
        <ul>
            <li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
            <li><div class="button"><div class="buttonContent"><button class="close" type="button">关闭</button></div></div></li>
        </ul>
    </div>
</div>
</form>










<div class="pageContent" style="height: 139px; overflow: auto;">
            
        <div class="panel collapse">
            <div class="panelHeader">
                <div class="panelHeaderContent">
                    <h1 style="cursor: move;">添加用户</h1><a href="" class="collapsable"></a>
                </div>
            </div>
            <div class="panelContent" style="height: 150px;">
            
                <form onsubmit="return validateCallback(this, navTabAjaxDone);" class="pageForm required-validate" action="<?php echo $this->URL;?>/insert?navTabId=<?php echo $this->MODULE;?>" method="post" novalidate="novalidate">
                    <div layouth="56" class="pageFormContent" style="height: 125px; overflow: auto;">
                        <p>
                            <label>名 称：</label>
                            <input name="name" class="required"  type="text"/>
                        </p>
                        <p>
                            <label>真实名称：</label>
                            <input type="text" alt="请输入名称" value="" size="30" class="required textInput" name="realname" id="realname_9837">
                        <label for="realname_9837" class="alt" style="width: 188px; top: 5px; left: 130px; opacity: 1; display: none;">请输入名称</label></p>
                        <p>
                            <label>地址：</label>
                            <textarea class="editor" name="address" rows="4" cols="75"></textarea>
                        </p>
                    </div>
                    <div class="formBar">
                        <ul>
                            <li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
                            <li>
                                <div class="button"><div class="buttonContent"><button class="close" type="button">取消</button></div></div>
                            </li>
                        </ul>
                    </div>
                </form>
                
            </div>

            <div class="panelFooter">
                <div class="panelFooterContent"></div>
            </div>
        </div>

</div>




