
<div class="pageContent" style="height: 139px; overflow: auto;">
            
        <div class="panel collapse">
            <div class="panelHeader">
                <div class="panelHeaderContent">
                    <h1 style="cursor: move;">添加标签</h1><a href="" class="collapsable"></a>
                </div>
            </div>
            <div class="panelContent" style="height: 150px;">
            
                <form onsubmit="return validateCallback(this, navTabAjaxDone);" class="pageForm required-validate" action="<?php echo $this->URL;?>/insert?navTabId=<?php echo $this->MODULE;?>" method="post" novalidate="novalidate">
                    <div layouth="56" class="pageFormContent" style="height: 125px; overflow: auto;">
                        <p>
                            <label>编 号：</label>
                            <input name="code" class="required digits" alt="请输入整数" type="text"/>
                        </p>
                        <p>
                            <label>名 称：</label>
                            <input type="text" alt="请输入名称" value="" size="30" class="required textInput" name="name" id="name_9837">
                        <label for="name_9837" class="alt" style="width: 188px; top: 5px; left: 130px; opacity: 1; display: none;">请输入名称</label></p>
                        <p>
                            <label>描 述：</label>
                            <textarea class="editor" name="description" rows="4" cols="75"></textarea>
                        </p>
                    </div>
                    <div class="formBar">
                        <ul>
                            <li><div class="buttonActive"><div class="buttonContent"><button type="submit">保存</button></div></div></li>
                            <li>
                                <div class="button"><div class="buttonContent"><button class="close" type="button">取消</button></div></div>
                            </li>
                        </ul>
                    </div>
                </form>
                
            </div>

            <div class="panelFooter">
                <div class="panelFooterContent"></div>
            </div>
        </div>

</div>




