<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" />
<title>内容管理系统</title>

<link href="dwz/themes/default/style.css" rel="stylesheet" type="text/css" />
<link href="dwz/themes/css/core.css" rel="stylesheet" type="text/css" />
<!--<link href="uploadify/css/uploadify.css" rel="stylesheet" type="text/css" />-->
<!--[if IE]>
<link href="themes/css/ieHack.css" rel="stylesheet" type="text/css" />
<![endif]-->

<script src="dwz/js/speedup.js" type="text/javascript"></script>
<script src="dwz/js/jquery-1.4.4.min.js" type="text/javascript"></script>
<script src="dwz/js/jquery.cookie.js" type="text/javascript"></script>
<script src="dwz/js/jquery.validate.js" type="text/javascript"></script>
<script src="dwz/js/jquery.bgiframe.js" type="text/javascript"></script>
<!--
<script src="xheditor/xheditor-1.1.9-zh-cn.min.js" type="text/javascript"></script>
<script src="uploadify/scripts/swfobject.js" type="text/javascript"></script>
<script src="uploadify/scripts/jquery.uploadify.v2.1.0.js" type="text/javascript"></script>
-->

<script src="dwz/js/dwz.min.js" type="text/javascript"></script>
<script src="dwz/js/dwz.regional.zh.js" type="text/javascript"></script>

<script type="text/javascript">
$(function(){
    DWZ.init("dwz/dwz.frag.xml", {
        loginUrl:"login_dialog.html", loginTitle:"登录",  // 弹出登录对话框
      loginUrl:"login.html",  // 跳到登录页面
        statusCode:{ok:1, error:0, timeout:301}, //【可选】
        pageInfo:{pageNum:"pageNum", numPerPage:"numPerPage", orderField:"orderField", orderDirection:"orderDirection"}, //【可选】
        debug:false,    // 调试模式 【true|false】
        callback:function(){
            initEnv();
            $("#themeList").theme({themeBase:"dwz/themes"}); // themeBase 相对于index页面的主题base路径
        }
    });
});
</script>
</head>

<body scroll="no">
    <div id="layout">
        <div id="header">
            <div class="headerNav">
                <a class="logo" href="#">内容管理系统</a>
                <ul class="nav">
                    <li><a href="changepwd.html" target="dialog" width="600">设置</a></li>
                    <li><a href="#">退出</a></li>
                </ul>
                <ul class="themeList" id="themeList">
                    <li theme="default"><div class="selected">蓝色</div></li>
                    <li theme="green"><div>绿色</div></li>
                    <li theme="purple"><div>紫色</div></li>
                    <li theme="silver"><div>银色</div></li>
                    <li theme="azure"><div>天蓝</div></li>
                </ul>
            </div>

        </div>

        <div id="leftside">
            <div id="sidebar_s">
                <div class="collapse">
                    <div class="toggleCollapse"><div></div></div>
                </div>
            </div>
            <div id="sidebar">
                <div class="toggleCollapse"><h2>主菜单</h2><div>收缩</div></div>

                <div class="accordion" fillSpace="sidebar">
                    <div class="accordionHeader">
                        <h2><span>Folder</span>基础信息管理</h2>
                    </div>
                    <div class="accordionContent">
                        <ul class="tree treeFolder">
                            <li><a href="keywords" target="navTab" rel="keywords">标签管理</a></li>
                        </ul>
                    </div>
                    <div class="accordionHeader">
                        <h2><span>Folder</span>采集信息管理</h2>
                    </div>
                    <div class="accordionContent">
                        <ul class="tree treeFolder treeCheck">

                        </ul>
                    </div>
                    <div class="accordionHeader">
                        <h2><span>Folder</span>报表分析</h2>
                    </div>
                    <div class="accordionContent">
                        <ul class="tree treeFolder treeCheck">

                        </ul>
                    </div>
                    <div class="accordionHeader">
                        <h2><span>Folder</span>系统管理</h2>
                    </div>
                    <div class="accordionContent">
                        <ul class="tree treeFolder">
                            <li><a href="user" target="navTab" rel="user">用户管理</a></li>
                            <li><a href="aclrole" target="navTab" rel="aclrole">角色管理</a></li>
                            <li><a href="aclresource" target="navTab" rel="aclresource">资源管理</a></li>
                        </ul>
                    </div>

                </div>

            </div>
        </div>
        <div id="container">
            <div id="navTab" class="tabsPage">
                <div class="tabsPageHeader">
                    <div class="tabsPageHeaderContent"><!-- 显示左右控制时添加 class="tabsPageHeaderMargin" -->
                        <ul class="navTab-tab">
                            <li tabid="main" class="main"><a href="javascript:;"><span><span class="home_icon">我的主页</span></span></a></li>
                        </ul>
                    </div>
                    <div class="tabsLeft">left</div><!-- 禁用只需要添加一个样式 class="tabsLeft tabsLeftDisabled" -->
                    <div class="tabsRight">right</div><!-- 禁用只需要添加一个样式 class="tabsRight tabsRightDisabled" -->
                    <div class="tabsMore">more</div>
                </div>
                <ul class="tabsMoreList">
                    <li><a href="javascript:;">我的主页</a></li>
                </ul>
                <div class="navTab-panel tabsPageContent layoutBox">
                    <div class="page lookupBox">

                        <div class="accountInfo">
                            <div class="alertInfo">
                                <h2>系统正常运行</h2>

                            </div>
                            <div class="right">
                                <p></p>
                                <p></p>
                            </div>
                            <p><span>管理系统</span></p>
                            <p></p>
                        </div>

                        <div class="pageFormContent" layoutH="80">

                        </div>

                    </div>

                </div>
            </div>
        </div>

    </div>

    <div id="footer">Copyright &copy; 2010 <a href="dwz/about.html" target="dialog">DWZ团队</a></div>

</body>
</html>